# Generated by Django 5.2.6 on 2025-09-03 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=10)),
                ('menopause_phase', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('goals', models.JSONField()),
                ('voice_preference', models.BooleanField(default=False)),
                ('communication_tone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
